<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="31444" started-at="2020-07-10T13:31:40Z" finished-at="2020-07-10T13:32:12Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="31444" started-at="2020-07-10T13:31:40Z" finished-at="2020-07-10T13:32:12Z">
      <class name="TestcaseScript.Test1">
        <test-method status="PASS" signature="openApp()[pri:0, instance:TestcaseScript.Test1@76b0bfab]" name="openApp" is-config="true" duration-ms="14277" started-at="2020-07-10T13:31:40Z" finished-at="2020-07-10T13:31:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openApp -->
        <test-method status="FAIL" signature="Test_Login()[pri:0, instance:TestcaseScript.Test1@76b0bfab]" name="Test_Login" duration-ms="6312" started-at="2020-07-10T13:31:55Z" finished-at="2020-07-10T13:32:01Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.fail(Assert.java:103)
at TestcaseScript.Test1.Test_Login(Test1.java:23)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Test_Login -->
        <test-method status="PASS" signature="closeApp(org.testng.ITestResult)[pri:0, instance:TestcaseScript.Test1@76b0bfab]" name="closeApp" is-config="true" duration-ms="10813" started-at="2020-07-10T13:32:01Z" finished-at="2020-07-10T13:32:12Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=Test_Login status=FAILURE method=Test1.Test_Login()[pri:0, instance:TestcaseScript.Test1@76b0bfab] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeApp -->
      </class> <!-- TestcaseScript.Test1 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
